### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Sidewinder92** [wootguy/PortalSpawner#1]
Hi wootguy,

I have been looking for this script since EntMod created portals are not working anymore. Great job on that script. How do I install this?

Regards,
Sidewinder92

**Comment by wootguy** [comment]
Hi, I just added instructions here:
https://github.com/wootguy/PortalSpawner#installation

**Comment by Sidewinder92** [comment]
Hi wootguy,

thank you so much for your response. Keep those amazing scripts going.

Regards,
Sidewinder92
