### ISSUE TITLE
Help with sprites

### ISSUE THREAD

**Issue by Cads182** [wootguy/PortalSpawner#2]
Hey w00t can you help me with one thing please? I recently created a sprite that could work for the 3 types of portals, simply changing the color would be enough, the problem is there's no set up for this, obviously, you had to use different sprites files, I would be very grateful if you can help me with that!, Thanks

**Comment by wootguy** [comment]
1. Replace [these paths](https://github.com/wootguy/PortalSpawner/blob/master/PortalSpawner.as#L433-L435) with the path to your sprite.
1. Edit the colors [here](https://github.com/wootguy/PortalSpawner/blob/master/PortalSpawner.as#L588-L599) / add whatever keyvalues you want.

**Comment by Cads182** [comment]
Thanks!
